SERVER_PORT: 9090
CONTEXT_PATH: /api

DATABASE_URL: localhost
DATABASE_PASSWORD: root
DATABASE_USERNAME: postgres
DATABASE_NAME: prop_rental_db
DATABASE_PORT: 5432

MAIL_HOST: sandbox.smtp.mailtrap.io
MAIL_PORT: 2525
MAIL_USERNAME: 1c3b5dbd53576c
MAIL_PASSWORD: be0fe5e67fa351