server:
  port: ${SERVER_PORT:9090}
  servlet:
    contextPath: ${CONTEXT_PATH:/api}

spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    url: jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types.print.banner: false
        format_sql: true