SERVER_PORT: 9090
CONTEXT_PATH: /api

DATABASE_URL: none
DATABASE_PASSWORD: none
DATABASE_USERNAME: none
DATABASE_NAME: none
DATABASE_PORT: none

MAIL_HOST: none
MAIL_PORT: none
MAIL_USERNAME: none
MAIL_PASSWORD: none