server:
  port: ${SERVER_PORT:9090}
  servlet:
    contextPath: ${CONTEXT_PATH:/api}

spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    url: jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types.print.banner: false
        format_sql: true

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  file:
#    path: ./logs/property-rent-pro.log
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

token:
  app:
    jwtSecret: mySuperSecretKeyForJWT1234
    jwtExpirationMs: 3600000 # 1 hour for access token